name: Deploy Portfolio to lazyta-toru.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウトします
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. rsync (高機能なファイル転送) を使ってサーバーにデプロイします
      - name: Deploy to server with rsync
        uses: burnett01/rsync-deployments@v7.1.0 # <- ★ 鉄板のアクションに変更
        with:
          # rsyncのオプション
          # -a (archive): 属性を保持 (推奨)
          # -v (verbose): 詳細を表示
          # -z (compress): 圧縮して転送
          # -r (recursive): 再帰的に
          # --delete: サーバー側の不要なファイルを削除
          switches: -avzr --delete
          
          # 転送元のファイル ( '.' はリポジトリ全体)
          path: .
          
          # 転送先サーバーのパス
          remote_path: /var/www/html/
          
          # サーバーのホスト名 (Secretsから)
          remote_host: ${{ secrets.REMOTE_HOST }}
          
          # サーバーのユーザー名 (Secretsから)
          remote_user: ${{ secrets.REMOTE_USER }}
          
          # SSHの秘密鍵 (Secretsから)
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

