name: Deploy Portfolio to lazyta-toru.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウトします
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. ★★★ これがホストキー確認（1分ハングアップ）問題を解決します ★★★
      # KNOWN_HOSTSシークレットを使って、サーバーの指紋を登録する
      - name: Create known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      # ★★★★★★★★★★★★★★★★★★

      # 3. rsync (高機能なファイル転送) を使ってサーバーにデプロイします
      - name: Deploy to server with rsync
        uses: burnett01/rsync-deployments@7.0.0
        with:
          # rsyncのオプション
          switches: -avzr --delete
          
          # 
          # rsh: "ssh -o StrictHostKeyChecking=no"  <--- ★★★ この行は削除しました ★★★
          # 
          
          # 転送元のファイル ( '.' はリポジトリ全体)
          path: .
          
          # 転送先サーバーのパス
          remote_path: /var/www/html/
          
          # ★★★ これがホスト名問題を解決します ★★★
          # シークレット経由ではなく、ホスト名を直接書き込む
          remote_host: lazyta-toru.net
          # ★★★★★★★★★★★★★

          # サーバーのユーザー名 (Secretsから)
          remote_user: ${{ secrets.REMOTE_USER }}
          
          # SSHの秘密鍵 (Secretsから)
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

