name: Deploy Portfolio to lazyta-toru.net

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. リポジトリのコードをチェックアウトします
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. rsync (高機能なファイル転送) を使ってサーバーにデプロイします
      - name: Deploy to server with rsync
        uses: SamKirkland/RSYNC-deploy-action@v4 # <- ★ アクションをこちらに変更
        with:
          # 転送元のファイル ( '.' はリポジトリ全体)
          SOURCE: "."
          
          # 転送先サーバー
          # ※ secrets.REMOTE_USER, secrets.REMOTE_HOST, サーバーパス を組み合わせます
          TARGET: "${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:/var/www/html/"
          
          # SSHの秘密鍵
          PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
          
          # rsyncのオプション (--delete でサーバー側の不要なファイルを削除)
          ARGS: "--delete"

